apiVersion: v1
kind: Service
metadata:
  name: aspdotnet-elb
  labels:
    app: aspdotnet
  namespace: default
spec:
  selector:
    app: aspdotnet
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 80
      port: 8000
      protocol: TCP
  type: LoadBalancer
  